#!/usr/bin/env python3
"""Turn ../../common/data/* into src/data.js.

The tables are NASM `db`/`dw` source, so rather than parse them, assemble them
with nasm and read the bytes back.  A wrapper emits a header of label offsets
first, which is how the slices below are found.  Whatever the assembler makes of
the expressions in the source - the `NT()` macro, the `CAM` macro - is what ends
up here, which is the whole point of going through nasm.
"""
import os, re, struct, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.normpath(os.path.join(HERE, '..', '..', '..', 'common', 'data'))
OUT = os.path.normpath(os.path.join(HERE, '..', 'src', 'data.js'))

LABELS = ['samples', 'orderList', 'patternList', 'channelList',
          'camera_table', 'theend']

WRAPPER = """\
bits 64
org 0
%s
%%include "samples.inc"
%%include "zik.asm"
%%macro CAM 1
    db %%1
%%endmacro
camera_table:
%%include "cameras.inc"
theend:
""" % '\n'.join('    dd %s' % l for l in LABELS)


def assemble():
    with tempfile.TemporaryDirectory() as tmp:
        asm, binf = os.path.join(tmp, 'w.asm'), os.path.join(tmp, 'w.bin')
        open(asm, 'w').write(WRAPPER)
        subprocess.run(['nasm', '-f', 'bin', '-I', DATA + os.sep, asm, '-o', binf],
                       check=True)
        return open(binf, 'rb').read()


def main():
    blob = assemble()
    n = len(LABELS)
    off = dict(zip(LABELS, struct.unpack_from('<%dI' % n, blob, 0)))
    seg = lambda a, b: blob[off[a]:off[b]]

    samples = seg('samples', 'orderList')
    tables = {
        'samples':      list(samples),
        'orderList':    list(seg('orderList', 'patternList')),
        'patternList':  list(seg('patternList', 'channelList')),
        'channelList':  list(seg('channelList', 'camera_table')),
        'camera_table': list(seg('camera_table', 'theend')),
    }

    # The shapes the port hard-codes.  A perxxor block is sixteen bytes, a
    # pattern is eight channel slots, a channel record is one instrument byte
    # plus twelve notes plus twelve effects.
    assert len(tables['samples']) == 8 * 16, len(tables['samples'])
    assert len(tables['orderList']) == 54, len(tables['orderList'])
    assert len(tables['patternList']) % 8 == 0
    assert len(tables['channelList']) % 25 == 0
    assert len(tables['camera_table']) == 37, len(tables['camera_table'])

    js = lambda v: '[' + ', '.join(str(x) for x in v) + ']'

    src = ['// Generated by tools/extract_data.py from ../../common/data - do not edit.',
           "// The intro's content, assembled by nasm and read back byte for byte.",
           '',
           '// Eight sixteen-byte perxxor blocks; see sgen.js for the layout.',
           'export const samples = %s;' % js(tables['samples']),
           '',
           '// The module: 54 orders of 12 rows over 8 channels (zik.asm).',
           'export const orderList = %s;' % js(tables['orderList']),
           'export const patternList = %s;' % js(tables['patternList']),
           'export const channelList = %s;' % js(tables['channelList']),
           '',
           '// Which camera is live during each 100-tick slice (cameras.inc).',
           'export const camera_table = %s;' % js(tables['camera_table']),
           '']
    open(OUT, 'w').write('\n'.join(src) + '\n')

    print('wrote %s' % OUT)
    for k, v in tables.items():
        print('  %-13s %d' % (k, len(v)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
